extern "C" {
#include "Collision/Shapes/b2ChainShapeJsBindings.h"
#include "Collision/Shapes/b2CircleShapeJsBindings.h"
#include "Collision/Shapes/b2EdgeShapeJsBindings.h"
#include "Collision/Shapes/b2PolygonShapeJsBindings.h"
#include "Dynamics/b2BodyJsBindings.h"
#include "Dynamics/b2WorldJsBindings.h"
#include "Dynamics/Joints/b2FrictionJointJsBindings.h"
#include "Dynamics/Joints/b2RevoluteJointJsBindings.h"
#include "Particle/b2ParticleSystemJsBindings.h"
}
#include "Collision/Shapes/b2ChainShapeJsBindings.cpp"
#include "Collision/Shapes/b2CircleShapeJsBindings.cpp"
#include "Collision/Shapes/b2EdgeShapeJsBindings.cpp"
#include "Collision/Shapes/b2PolygonShapeJsBindings.cpp"
#include "Dynamics/b2BodyJsBindings.cpp"
#include "Dynamics/b2WorldJsBindings.cpp"
#include "Dynamics/Joints/b2FrictionJointJsBindings.cpp"
#include "Dynamics/Joints/b2RevoluteJointJsBindings.cpp"
#include "Particle/b2ParticleSystemJsBindings.cpp"
